### ISSUE TITLE
commands list method, function

### ISSUE THREAD

**Issue by CaloloCosta** [Ninja243/JSBSD#1]
// listing all the commands available in the terminal
function commands(){
  let commands =  ["Command1","Command2","Commandn"];
  for(let i = 0; i < commands.length; i++){
    r += commands[i]+"\n";
  }
  return r;
}
// that is in runCMD method
if(cmd == 'compgen -c' || cmd == 'commands'){
  console.log(commands());
}

**Comment by Ninja243** [comment]
Hey there thanks for taking the time to look over my code!

As explained in the email I sent, this doesn't seem to be an issue with this code as the shell this is emulating [does not seem to have support for compgen](https://www.freebsd.org/cgi/man.cgi?query=compgen&apropos=0&sektion=0&manpath=FreeBSD+11.2-RELEASE+and+Ports&arch=default&format=html). Therefore, I'm closing this issue. Feel free to fork this repo if you would like to add this anyway.
